### PR TITLE
987_Vertical_Order_Traversal_of_a_Binary_Tree

### PR DESCRIPTION
**Pull request by sonwanigaurav**
Solution for problem https://leetcode.com/problems/vertical-order-traversal-of-a-binary-tree/

### CODE REVIEW

**Comment by jayesh-kaza** [comment]
Hey @sonwanigaurav Can you make it as a '.java' extension file

**Comment by sonwanigaurav** [comment]
sure

**Comment by sonwanigaurav** [comment]
I have made it as '.java' extension file

**Comment by jayesh-kaza** [comment]
Thanks @sonwanigaurav :smile:

**Pull request merged**
